project:
  type: website
  output-dir: docs

website:
  title: "wrnet"
  navbar:
    background: "#0479A8"
    left:
      - href: index.qmd
        text: Introduction

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    linkcolor: "#C5050C"
    backgroundcolor: "#FFFFFF"
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
      gutter-width: 1.5rem
    filters:
      - newpagelink.lua



